### ISSUE TITLE
Large put() over federation leaves "valid" replicas of incorrect size and checksum when interrupted

### ISSUE THREAD

**Issue by kjsanger** [irods/python-irodsclient#378] opened 2022-07-26 15:34 UTC
iRODS server: `4.2.7`, federated
PRC: `1.1.4`

What did you do:

`put` a 50 GiB file from a client connected to zone `Sanger1` into federated zone `seq` and raise `SIGINT` part way through the operation.

What did you expect to happen:

The operation to fail and if any data object was created, it not be marked valid.

What happend:

The operation failed, but the resulting data object _is_ marked valid:

```
 ils -L /seq/test/kdj/50GB_zero
  kdj               0 root;replicate;sanger;seq-green;green7;irods-seq-sb07-ddn-bd12b-vd4-2  12499025920 2022-07-15.16:27 & 50GB_zero
    a1cdc59e05f7fb9e8d5b933854e607aa    generic    /irods-seq-sb07-ddn-bd12b-vd4-2/test/kdj/50GB_zero
  kdj               1 root;replicate;remote;seq-red;red2;irods-seq-ig12-sdf  12499025920 2022-07-15.16:29 & 50GB_zero
    a1cdc59e05f7fb9e8d5b933854e607aa    generic    /irods-seq-ig12-sdf/test/kdj/50GB_zero
```

The checksum is actually `e7f4706922e1edfdb43cd89eb1af606d`.

```
#!/usr/bin/env python

import os
import ssl
from irods.session import iRODSSession

try:
    env_file = os.environ["IRODS_ENVIRONMENT_FILE"]
except KeyError:
    env_file = os.path.expanduser("~/.irods/irods_environment.json")

ssl_context = ssl.create_default_context(
    purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None
)
ssl_settings = {"ssl_context": ssl_context}

with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    obj = session.data_objects.put("50GB_zero", "/seq/test/kdj/50GB_zero",
                                   return_data_object=True, num_threads=16)
```

**Comment by kjsanger** [comment] 2022-07-26 15:43
Actually, federation may be a red herring - I get the same behaviour when logged directly into the zone to which I am `put`ing.

**Comment by trel** [comment] 2022-07-26 16:35
I think a lot of this is handled with 4.2.8 or later...   Seems like we might already have a test for this?  @alanking ?

**Comment by d-w-moore** [comment] 2022-07-26 17:05
I'm assuming iput doesn't do this because the PUT api (as opposed to the PRC's open/read-write/close MO) makes sure to finalize properly. And, if it's happening only with very large files (as stated in the setup) it's the parallel put dropping the balls in the wrong order, probably... will be curious to see what happens if #threads is forced to 1

**Comment by d-w-moore** [comment] 2022-07-26 17:06
Also SSL might play a part?

**Comment by trel** [comment] 2022-07-26 17:46
We should be able to test this directly with Ctrl-C on a PRC1.1.4 script talking to 4.2.7 and then 4.2.9+.

**Comment by alanking** [comment] 2022-07-26 18:39
Drat, @kjsanger is too fast :)

I tried to reproduce this, but instead of a 50GB file with 0's, I used a 1GB file using `truncate`. I used Ctrl+C/keyboard interrupt to introduce the `SIGINT`. Hopefully that's enough to trigger similar behavior...

In a container running 4.2.7...
```bash
$ python3 put.py 
^CTraceback (most recent call last):
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 162, in put
    o.write(chunk)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/data_object.py", line 194, in write
    return self.conn.write_file(self.desc, b.tobytes())
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 581, in write_file
    response = self.recv()
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 113, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 270, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 180, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "put.py", line 19, in <module>
    return_data_object=True, num_threads=16)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 162, in put
    o.write(chunk)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/data_object.py", line 183, in seek
    return self.conn.seek_file(self.desc, offset, whence)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 599, in seek_file
    offset = response.get_main_message(FileSeekResponse).offset
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 375, in get_main_message
    raise self.ResponseNotParseable( message )
irods.message.ResponseNotParseable: Server response was None while parsing as [<class 'irods.message.FileSeekResponse'>]
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc     83886080 2022-07-26.18:21 & 1GB_trunc
```
The created replica is not the right size and it is incorrectly marked good.

In a container running 4.2.8...
```bash
$ python3 put.py 
^CTraceback (most recent call last):
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 162, in put
    o.write(chunk)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/data_object.py", line 194, in write
    return self.conn.write_file(self.desc, b.tobytes())
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 581, in write_file
    response = self.recv()
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 113, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 270, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 180, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "put.py", line 19, in <module>
    return_data_object=True, num_threads=16)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 162, in put
    o.write(chunk)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/data_object.py", line 183, in seek
    return self.conn.seek_file(self.desc, offset, whence)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 599, in seek_file
    offset = response.get_main_message(FileSeekResponse).offset
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 375, in get_main_message
    raise self.ResponseNotParseable( message )
irods.message.ResponseNotParseable: Server response was None while parsing as [<class 'irods.message.FileSeekResponse'>]
-bash-4.2$ ils -l
/tempZone/home/rods:
  rods              0 demoResc     33554432 2022-07-26.18:31 & 1GB_trunc
```
The created replica is not the right size and it is incorrectly marked good.

In a container running 4.2.11...
```bash
$ python3 put.py 
^CTraceback (most recent call last):
  File "put.py", line 20, in <module>
    return_data_object=True, num_threads=16)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 154, in put
    open_options = options ):
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 247, in parallel_put
    queueLength = (DEFAULT_QUEUE_DEPTH if progressQueue else 0)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/parallel.py", line 484, in io_main
    _queueLength = queueLength)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/parallel.py", line 387, in _io_multipart_threaded
    kw.REPLICA_TOKEN_KW: replica_token })
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 332, in open
    desc = conn.recv().int_info
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/connection.py", line 113, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 270, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/var/lib/irods/.local/lib/python3.6/site-packages/irods/message/__init__.py", line 180, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
KeyboardInterrupt
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc     91860128 2022-07-26.18:37 X 1GB_trunc
```
The created replica is not the right size, and it is correctly marked stale.

Bonus note: I tried to install 1.1.4 using python2 and got some syntax errors. I think we might need to nail down our PrettyTable version if we want to continue supporting python2.

**Comment by kjsanger** [comment] 2022-07-26 18:48
Thanks for your patience - I try not to report things that are simply a consequence of us being on `4.2.7`, but sometimes hard to tell what's the correct expectation, given the the PRC supports multiple iRODS versions.

**Comment by trel** [comment] 2022-07-26 19:06
Excellent... so... this one might be 'no action necessary'... ?

**Comment by kjsanger** [comment] 2022-07-26 19:13
I think so, thanks - action is to move to `4.2.12`  / `4.3.0`! There are notes about various iRODS versions in the README already and it would be helpful to have an additional note to the effect that PRC `put` != `iput` and the consequences of how that interacts with different iRODS versions.

**Comment by d-w-moore** [comment] 2022-10-14 03:36
Ok, well I guess we have a choice then.  
   - Admit 4.2.7 is broken and everyone should upgrade now, and close this issue.  Or 
   - fix PRC for the benefit of those still finding themselves in 4.2.7 land.

**Comment by trel** [comment] 2022-10-22 17:23
Closing - no action necessary.   The server got smarter, and PRC is just a client.

**Closed by trel** 2022-10-22 17:23 UTC
