### ISSUE TITLE
hostname redirection in the client should be off by default

### ISSUE THREAD

**Issue by d-w-moore** [irods/python-irodsclient#627] opened 2024-09-24 15:27 UTC
Applications should be able to freely open a data object without the client redirection coming in the way.  This has turned out to be a problem because 
   - the redirection feature isn't well documented (#626 )
   - when the feature is on, server hostnames are passed to the client for connection purposes which may not be reachable by the client.

Suggestions:
   - the feature should be disabled by default for principle of least surprise-
   - `data_object.open()`'s `allow_redirect` option can be used to override that default
   - optionally, a setting could be added , i.e. `irods.client_configuration.data_objects.allow_redirect` as a global flag that tells PRC to default to `allow_redirect = True` by default.  A similar setting already exists for the auto-closing of data objects.

**Comment by alanking** [comment] 2024-09-26 19:26
Just noting for posterity: While this is marked as a duplicate of #617, it has its own fix in #629 so we should not close it until that work has been merged.

**Comment by trel** [comment] 2024-09-26 19:27
yes, sorry - agreed.   still awaiting the fix to be merged.

**Comment by alanking** [comment] 2024-10-04 15:18
@d-w-moore - Please close if complete. Thanks

**Closed** 2024-10-04 16:10 UTC
Labels: bug, duplicate
