### ISSUE TITLE
irods_ssl_verify_server set to "cert" apparently not applied

### ISSUE THREAD

**Issue by jpmcfarland** [irods/python-irodsclient#382] opened 2022-08-25 12:55 UTC
Whether `"irods_ssl_verify_server": "cert"` is in the `irods_environment.json` file or as an argument to `iRODSSession` (`irods_ssl_verify_server="cert"` or `ssl_verify_server="cert"`), it does not appear to be applied.  In a high availability arrangement where the connection is passed to an iRODS server with a different hostname, setting the verification to "cert" is required and works fine with the iCommands.  When a connection is made after a PRC session is instantiated, however, the error below is seen.

A simple workaround of connecting directly to an iRODS server is effective, though not ideal.  

```python
---------------------------------------------------------------------------
SyntaxError                               Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/irods/session.py in server_version(self)
    163             reported_vsn = os.environ.get("PYTHON_IRODSCLIENT_REPORTED_SERVER_VERSION","")
--> 164             return tuple(ast.literal_eval(reported_vsn))
    165         except SyntaxError:  # environment variable was malformed, empty, or unset

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ast.py in literal_eval(node_or_string)
     61     if isinstance(node_or_string, str):
---> 62         node_or_string = parse(node_or_string, mode='eval')
     63     if isinstance(node_or_string, Expression):

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ast.py in parse(source, filename, mode, type_comments, feature_version)
     49     # Else it should be an int giving the minor version for 3.x.
---> 50     return compile(source, filename, mode, flags,
     51                    _feature_version=feature_version)

SyntaxError: unexpected EOF while parsing (<unknown>, line 0)

During handling of the above exception, another exception occurred:

StopIteration                             Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/irods/session.py in __server_version(self)
    169         try:
--> 170             conn = next(iter(self.pool.active))
    171             return conn.server_version

StopIteration: 

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/irods/pool.py in get_connection(self)
     58             try:
---> 59                 conn = self.idle.pop()
     60 

KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

SSLCertVerificationError                  Traceback (most recent call last)
<ipython-input-3-1459a0dfc7c9> in <module>
----> 1 coll = sess.collections.get('/testZone/home/user')

~/.local/lib/python3.9/site-packages/irods/manager/collection_manager.py in get(self, path)
     19              else (False,)
     20         for rep in repeats:
---> 21             query = self.sess.query(Collection).filter(*filters)
     22             try:
     23                 result = query.one()

~/.local/lib/python3.9/site-packages/irods/session.py in query(self, *args)
    140 
    141     def query(self, *args):
--> 142         return Query(self, *args)
    143 
    144     @property

~/.local/lib/python3.9/site-packages/irods/query.py in __init__(self, sess, *args, **kwargs)
     42             if isinstance(arg, type) and issubclass(arg, Model):
     43                 for col in arg._columns:
---> 44                     if self.sess.server_version >= col.min_version:
     45                         self.columns[col] = 1
     46             elif isinstance(arg, Column):

~/.local/lib/python3.9/site-packages/irods/session.py in server_version(self)
    164             return tuple(ast.literal_eval(reported_vsn))
    165         except SyntaxError:  # environment variable was malformed, empty, or unset
--> 166             return self.__server_version()
    167 
    168     def __server_version(self):

~/.local/lib/python3.9/site-packages/irods/session.py in __server_version(self)
    171             return conn.server_version
    172         except StopIteration:
--> 173             conn = self.pool.get_connection()
    174             version = conn.server_version
    175             conn.release()

~/.local/lib/python3.9/site-packages/irods/pool.py in method_(self, *s, **kw)
     13     def deco(method):
     14         def method_(self,*s,**kw):
---> 15             ret = method(self,*s,**kw)
     16             setattr(self,attrname,ret)
     17             return ret

~/.local/lib/python3.9/site-packages/irods/pool.py in get_connection(self)
     73                     logger.debug("Created new connection with id: {}".format(id(conn)))
     74             except KeyError:
---> 75                 conn = Connection(self, self.account)
     76                 logger.debug("No connection found in idle set. Created a new connection with id: {}".format(id(conn)))
     77 

~/.local/lib/python3.9/site-packages/irods/connection.py in __init__(self, pool, account)
     60         self.account = account
     61         self._client_signature = None
---> 62         self._server_version = self._connect()
     63         self._disconnected = False
     64 

~/.local/lib/python3.9/site-packages/irods/connection.py in _connect(self)
    280 
    281         if neg_result == USE_SSL:
--> 282             self.ssl_startup()
    283 
    284         return version_msg.get_main_message(VersionResponse)

~/.local/lib/python3.9/site-packages/irods/connection.py in ssl_startup(self)
    183 
    184         # Wrap socket with context
--> 185         wrapped_socket = context.wrap_socket(self.socket, server_hostname=host)
    186 
    187         # Initial SSL handshake

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    498         # SSLSocket class handles server_hostname encoding before it calls
    499         # ctx._wrap_socket()
--> 500         return self.sslsocket_class._create(
    501             sock=sock,
    502             server_side=server_side,

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1038                         # non-blocking
   1039                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040                     self.do_handshake()
   1041             except (OSError, ValueError):
   1042                 self.close()

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py in do_handshake(self, block)
   1307             if timeout == 0.0 and block:
   1308                 self.settimeout(None)
-> 1309             self._sslobj.do_handshake()
   1310         finally:
   1311             self.settimeout(timeout)

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for '<FQDN REDACTED>'. (_ssl.c:1129)
```

**Comment by d-w-moore** [comment] 2022-08-25 13:26
hello JP,  - For the above error dump, could you give us the call as made from the application and / or the contents of the irods_environment.json?

**Comment by jpmcfarland** [comment] 2022-08-31 13:09
```python
import irods.session
import os
import ssl

env_file = os.path.expanduser('~/.irods/irods_environment.json')
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
ssl_settings = {'ssl_context': ssl_context}
sess = irods.session.iRODSSession(irods_env_file=env_file, **ssl_settings)

coll = sess.collections.get('/testZone/home/user')
```

~/.irods/irods_environment.json

```json
{
    "irods_authentication_scheme": "PAM",
    "irods_host": "test_host",
    "irods_port": 1247,
    "irods_zone_name": "testZone",
    "irods_default_resource": "defaultResc",
    "irods_user_name": "user",
    "irods_home": "/testZone/home/user",
    "irods_cwd": "/testZone/home/user",
    "irods_client_server_negotiation": "request_server_negotiation",
    "irods_client_server_policy": "CS_NEG_REQUIRE",
    "irods_connection_pool_refresh_time_in_seconds": 300,
    "irods_default_hash_scheme": "SHA256",
    "irods_default_number_of_transfer_threads": 4,
    "irods_encryption_algorithm": "AES-256-CBC",
    "irods_encryption_key_size": 32,
    "irods_encryption_num_hash_rounds": 16,
    "irods_encryption_salt_size": 8,
    "irods_match_hash_policy": "compatible",
    "irods_maximum_size_for_single_buffer_in_megabytes": 32,
    "irods_ssl_verify_server": "cert",
    "irods_transfer_buffer_size_for_parallel_transfer_in_megabytes": 4,
    "schema_name": "irods_environment",
    "schema_version": "v3"
}
```

`test_host` here is an alias for a load balancer in front of several iRODS 4.2.10 servers, all with different hostnames, whose certificate CN is that of the host and not of the load balancer.  All servers have FQDNs.  If any of these iRODS servers are connected to directly in the same manner, no error occurs.

**Comment by d-w-moore** [comment] 2022-09-01 11:47
Thanks! Will work to reproduce.

**Comment by d-w-moore** [comment] 2022-10-14 20:06
Hi JP. It does seem that because of [this line](https://github.com/irods/python-irodsclient/blob/0afbe3752f97faee9dd55d40f03faa81a2e7b0ca/irods/connection.py#L173) in the Python client that the `ssl_verify_server` setting would not be honored, but  instead the ssl socket would be instantiated with the default ssl context provided in your code. The default context sets check_hostname to True.  Have you tried omitting the default_context from the argument list to iRODSSession and letting the library generate the ssl context (as it does in the AttributeError exception catch clause just below the above quoted line)?

**Comment by d-w-moore** [comment] 2022-10-16 14:20
@jpmcfarland - Oops, I neglected to tag you in the post just above ^^^ : )

**Comment by jpmcfarland** [comment] 2022-10-18 11:16
Yes.  Removing the default context here does indeed work.  What is the recommended procedure then?  Provide no SSL context?  Set `check_hostname = False` if you need to?  Both work.

**Comment by d-w-moore** [comment] 2022-10-18 14:28
Looking into that now.  The default context way of doing things is probably in some contention with the policy of respecting the client environment.

**Comment by d-w-moore** [comment] 2022-10-19 06:35
@jpmcfarland - For now, the answer seems to be (as you said) not to provide an SSL context, and the client will provide one in its place. The more complete answer is that we probably should have a 
way to generate an appropriate SSLContext based on the client environment and/or keyword args to the iRODSSession( ) call. Looking at those possibilities now.

**Comment by d-w-moore** [comment] 2022-11-11 14:17
> ... The more complete answer is that we probably should have a way to generate an appropriate SSLContext based on the client environment and/or keyword args to the iRODSSession( ) call. Looking at those possibilities now.
hi again @jpmcfarland ,
Just a heads-up.
#407 will likely be merged soon and will be the general solution for ensuring that 
`irods_ssl_verify_server ` and other irods_ssl_* options have their intended effect when the Python library is "asked" (by the omission of the `ssl_context` keyword parameter) to generate its own ssl context internally.

**Comment by jpmcfarland** [comment] 2022-11-11 14:29
Thanks!

**Comment by d-w-moore** [comment] 2022-11-15 01:42
@jpmcfarland - I am thinking we can probably close this issue, since the main branch now has a solution for #406 (a patched version of the PRC's default SSLContext factory that now aims to satisfy the requirements of all `irods_ssl_*` config options).  Would you be interested in testing [tip of main](https://github.com/irods/python-irodsclient/tree/9a79d9eded829763a3b78754118c555800a5193a) with your applications to make sure it does not break them?

**Comment by d-w-moore** [comment] 2022-11-16 14:04
Closing for the time being, @jpmcfarland, we'll reopen if you have any concerns....

**Closed by d-w-moore** 2022-11-16 14:04 UTC
