### ISSUE TITLE
Large put() times-out with NetworkException: Could not receive server response

### ISSUE THREAD

**Issue by jpmcfarland** [irods/python-irodsclient#377] opened 2022-07-20 14:44 UTC
When transferring extra large files (usually > 50GB, but can be less) with `put()`, the transfer can time-out ending in a `NetworkException: Could not receive server response`.  This may be due, at least in part, to a lack of redirected connection to a resource server (see #375) combined with replicative resources.

With the `iput` iCommand on larger files, the connection is redirected to the resource server.  When the resource used is a replicative resource, once the file is nearly transferred to the first resource, it is replicated to the next resource in full prior to the program exiting.  This assumes only one replication.  The same thing happens with `put()`, but the data must be transferred via the catalog server.  It may be that while waiting for this return a time-out occurs somewhere or perhaps an incorrect response is received.

The PRC version is 1.0.0 and the iRODS version on the server is 4.2.10.  Below is a traceback of a typical error:

```python
In [3]: s.data_objects.put('100GB/test7_rhhr5hgh.dat', '/testZone/home/jpm
   ...: /100GB/test7_rhhr5hgh.dat', num_threads=16)
   ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/irods/message/__init__.py in _recv_message_in_len(sock, size)
     29         try:
---> 30             buf = sock.recv(size_left, socket.MSG_WAITALL)
     31         except (AttributeError, ValueError):

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py in recv(self, buflen, flags)
   1222             if flags != 0:
-> 1223                 raise ValueError(
   1224                     "non-zero flags not allowed in calls to recv() on %s" %

ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>

During handling of the above exception, another exception occurred:

timeout                                   Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/irods/connection.py in recv(self)
     95         try:
---> 96             msg = iRODSMessage.recv(self.socket)
     97         except socket.error:

~/.local/lib/python3.9/site-packages/irods/message/__init__.py in recv(sock)
     94         # rsp_header_size = sock.recv(4, socket.MSG_WAITALL)
---> 95         rsp_header_size = _recv_message_in_len(sock, 4)
     96         rsp_header_size = struct.unpack(">i", rsp_header_size)[0]

~/.local/lib/python3.9/site-packages/irods/message/__init__.py in _recv_message_in_len(sock, size)
     31         except (AttributeError, ValueError):
---> 32             buf = sock.recv(size_left)
     33         except OSError as e:

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py in recv(self, buflen, flags)
   1225                     self.__class__)
-> 1226             return self.read(buflen)
   1227         else:

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/ssl.py in read(self, len, buffer)
   1100             else:
-> 1101                 return self._sslobj.read(len)
   1102         except SSLError as x:

timeout: The read operation timed out

During handling of the above exception, another exception occurred:

NetworkException                          Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/irods/manager/data_object_manager.py in put(self, local_path, irods_path, return_data_object, num_threads, **options)
    114                 f.close()
--> 115                 if not self.parallel_put( local_path, (obj,o), num_threads = num_threads,
    116                                           target_resource_name = options.get(kw.RESC_NAME_KW,'') or

~/.local/lib/python3.9/site-packages/irods/manager/data_object_manager.py in parallel_put(self, file_, data_or_path_, async_, num_threads, target_resource_name, progressQueue)
    165 
--> 166         return parallel.io_main( self.sess, data_or_path_, parallel.Oper.PUT | (parallel.Oper.NONBLOCKING if async_ else 0), file_,
    167                                  num_threads = num_threads, target_resource_name = target_resource_name,

~/.local/lib/python3.9/site-packages/irods/parallel.py in io_main(session, Data, opr_, fname, R, **kwopt)
    399     queueLength = kwopt.get('queueLength',0)
--> 400     retval = _io_multipart_threaded (Operation, (Data, Io), replica_token, resc_hier, session, fname, total_bytes,
    401                                      num_threads = num_threads,

~/.local/lib/python3.9/site-packages/irods/parallel.py in _io_multipart_threaded(operation_, dataObj_and_IO, replica_token, hier_str, session, fname, total_size, num_threads, **extra_options)
    339     else:
--> 340         bytecounts = [ f.result() for f in futures ]
    341         return sum(bytecounts), total_size

~/.local/lib/python3.9/site-packages/irods/parallel.py in <listcomp>(.0)
    339     else:
--> 340         bytecounts = [ f.result() for f in futures ]
    341         return sum(bytecounts), total_size

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    444                 elif self._state == FINISHED:
--> 445                     return self.__get_result()
    446                 else:

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    389             try:
--> 390                 raise self._exception
    391             finally:

/software/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/concurrent/futures/thread.py in run(self)
     51         try:
---> 52             result = self.fn(*self.args, **self.kwargs)
     53         except BaseException as exc:

~/.local/lib/python3.9/site-packages/irods/parallel.py in _io_part(objHandle, range_, file_, opr_, mgr_, thread_debug_id, queueObject)
    290         thread_debug_id = str(threading.currentThread().ident)
--> 291     return ( _copy_part (file_, objHandle, length, queueObject, thread_debug_id, mgr_) if Operation.isPut()
    292         else _copy_part (objHandle, file_, length, queueObject, thread_debug_id, mgr_) )

~/.local/lib/python3.9/site-packages/irods/parallel.py in _copy_part(src, dst, length, queueObject, debug_info, mgr)
    236     file_.close()
--> 237     mgr.remove_io( obj_ ) # 1. closes obj if it is not the mgr's initial descriptor
    238                           # 2. blocks at barrier until all transfer threads are done copying

~/.local/lib/python3.9/site-packages/irods/parallel.py in remove_io(self, Io)
    276         self.exit_barrier.wait()
--> 277         if is_initial: self.finalize()
    278 

~/.local/lib/python3.9/site-packages/irods/parallel.py in finalize(self)
    279     def finalize(self):
--> 280         self.initial_io.close()
    281 

~/.local/lib/python3.9/site-packages/irods/data_object.py in close(self)
    165         if self.finalize_on_close or not self._close_replica():
--> 166             self.conn.close_file(self.desc, **self.options)
    167         self.conn.release()

~/.local/lib/python3.9/site-packages/irods/connection.py in close_file(self, desc, **options)
    570         self.send(message)
--> 571         self.recv()
    572 

~/.local/lib/python3.9/site-packages/irods/connection.py in recv(self)
     99             self.release(True)
--> 100             raise NetworkException("Could not receive server response")
    101         if msg.int_info < 0:

NetworkException: Could not receive server response

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
ValueError: flush of closed file

During handling of the above exception, another exception occurred:

NetworkException                          Traceback (most recent call last)
<ipython-input-3-8f1682e6d1f7> in <module>
----> 1 s.data_objects.put('100GB/test7_rhhr5hgh.dat', f'/testrug/home/j.p.mc.farland@rug.nl/iBridges/100GB/test7_rhhr5hgh.dat', num_threads=16)

~/.local/lib/python3.9/site-packages/irods/manager/data_object_manager.py in put(self, local_path, irods_path, return_data_object, num_threads, **options)
    122                     options[kw.OPR_TYPE_KW] = 1 # PUT_OPR
    123                 for chunk in chunks(f, self.WRITE_BUFFER_SIZE):
--> 124                     o.write(chunk)
    125 
    126         if kw.ALL_KW in options:

~/.local/lib/python3.9/site-packages/irods/data_object.py in close(self)
    164     def close(self):
    165         if self.finalize_on_close or not self._close_replica():
--> 166             self.conn.close_file(self.desc, **self.options)
    167         self.conn.release()
    168         super(iRODSDataObjectFileRaw, self).close()

~/.local/lib/python3.9/site-packages/irods/connection.py in close_file(self, desc, **options)
    569 
    570         self.send(message)
--> 571         self.recv()
    572 
    573     def temp_password(self):

~/.local/lib/python3.9/site-packages/irods/connection.py in recv(self)
     98             logger.error("Could not receive server response")
     99             self.release(True)
--> 100             raise NetworkException("Could not receive server response")
    101         if msg.int_info < 0:
    102             try:

NetworkException: Could not receive server response
```

**Comment by korydraughn** [comment] 2022-07-20 15:44
We will look into it.

**Comment by trel** [comment] 2022-07-20 20:52
Can you try the same test with the latest PRC 1.1.4?

I'm hoping that's not too much of a burden to ask.

**Comment by jpmcfarland** [comment] 2022-07-20 20:56
That should be manageable . . . tomorrow.

**Comment by jpmcfarland** [comment] 2022-07-21 08:23
Easy peasy!  PRC version 1.1.4 give the same results.  I have not tested the limits, but file size between 50GB and 100GB causes this.  I will try extending the time by reducing the number of threads to see if I can find a length of time over which it fails.

**Comment by jpmcfarland** [comment] 2022-07-21 08:53
I forgot to mention, in all my testing, the initial replica made it to the resource server in whole and matched the file that was uploaded, despite the errors.

I uploaded ~50GB files with threads of 16, 8, 4, 2, and 1 and still no error.  The respective times were (approximately) 1:30, 2:00, 2:30, 4:30, and 9:00 minutes, but there was some variation.  I will attach an example screen capture from Grafana for the catalog server for reference.

**Comment by jpmcfarland** [comment] 2022-07-21 09:27
Here is a screenshot showing the various transfers.  The last 6 show the transfers mentioned above.

![Screen Shot 2022-07-21 at 10 50 18](https://user-images.githubusercontent.com/13783312/180178724-68f85f16-570c-4090-837e-2889132aadbf.png)

**Comment by trel** [comment] 2022-07-21 13:32
Yes, I think this feels like an idle connection on the 'other' hop - we're not using keepalives enough/correctly and/or we should be redirecting like `iput/iget` (#375).

As a test of this theory, you can try putting a sufficiently large file to a resource that is not under replication, and the single replica should land correctly and return cleanly, regardless of time/size.  If this works, then the 'waiting for the other replica(s) to complete' is silent enough and probably triggering a TCP timeout.

**Comment by jpmcfarland** [comment] 2022-07-21 15:34
Okay.  I'll give it a try.

**Comment by jpmcfarland** [comment] 2022-07-21 18:06
I just finished `put()`ing a TB of 100GB files without any problems to a very simple resource:

```
testResc:passthru
└── testVolume:unixfilesystem
```

It indeed seems like there is a time-out somewhere when replicating large files with a replication resource.

Is there a reason that the exit waits until the resource finishes the replication?  I think of a resource-triggered replication as a server process, not a client process, but clearly it isn't.  Is it possible to allow the put process of the initial replica to be independent of the replication when it is triggered by the resource like this?

**Comment by trel** [comment] 2022-07-21 18:08
The replication resource is a synchronous policy invocation on the part of the sysadmin.

If you're interested in asynchronous replication, you would use a delay() call in a post pep to enqueue a replication - in which case the prompt would be returned immediately to the caller (and in this case, the client).

**Comment by jpmcfarland** [comment] 2022-07-21 18:11
Okay!  Something to think about, certainly.  I hope that would not be necessary to avoid this issue.  I expect a well placed keep-alive or similar would be in order here.

**Comment by trel** [comment] 2022-07-21 18:13
Yes, we still have a bug in the timeout somewhere.     But you can design around it a bit (with async behavior) if really large files are something that you know this system will need to support.

**Comment by jpmcfarland** [comment] 2022-07-21 18:28
Indeed.  This size is not very common in our system, however.  The tester who found this was uploading a 64GB file.  I'll ask why to see if there is a significant use case.  Either way, it is an interesting solution to test.

**Comment by trel** [comment] 2022-07-21 18:30
Yes - good.

And a runtime decision to use sync or async replication *could* be dependent on uploaded file size as well (or any other input available to the policy logic).

**Comment by jpmcfarland** [comment] 2022-07-21 20:04
Way ahead of you.  I already have rule logic for a compound resource archiving large files to tape and small files elsewhere.  I can easily adapt it for this.

My only concern is that one branch previously attached to each replication resources will have to be a root node that users can configure to use directly.  I'd really like to avoid that possibility.  I wonder if it is feasible to misuse a compound resource for the async if only one replication is required?

**Comment by trel** [comment] 2022-07-21 20:39
one possibility... you could have a deferred node above the two sides of your tree with different behaviors... and you could have one side of the tree or the other 'win' based on incoming file size.

**Comment by jpmcfarland** [comment] 2022-07-21 20:57
That's also an idea.  So many ideas, so little time!  Tonight, anyway ;)

**Comment by d-w-moore** [comment] 2022-10-24 12:45
@jpmcfarland   I have just attempted to reproduce, using the replication resource and `tc` to slow down my local network - but to no avail, sadly.

Is it possible this is a firewall thing, as @kript suggested just above?  Has perhaps your operating system or iRODS server been tweaked / configured in any way, with regard to socket timeout parameters?

**Comment by jpmcfarland** [comment] 2023-02-15 23:37
This issue got backgrounded until during recent testing it reared its ugly head again.

I'm not sure about firewall timeouts, but our `tcp_keepalive_time` is only 120 seconds.  That sounds like it might be worth tinkering with.

**Comment by jpmcfarland** [comment] 2023-02-16 04:57
We changed to this a yea and a half ago because of transfer issues we already had.  We saw it here: irods/irods#3824

**Comment by d-w-moore** [comment] 2023-02-16 15:02
I might try and reproduce it again.  As I recall however, the changing of `tcp_keepalive_time` did not affect the outcome when I last tried on the replication-resource / `tc`-slowed setup (which I ref'd in a previous comment here). @jpmcfarland - if there are any other factors you could think of, or simpler configurations on which you've reproduced the problem, it might be helpful to note these.

**Comment by mstfdkmn** [comment] 2023-03-14 08:46
Hi, we have seen the same issue with irods4.3.0 and PRC 1.1.6. However I should state that we could not reproduce it consistently while uploading data- in one of our zones we could reproduce with an upload of 10GB while we reproduced it with 50 GB in another zone. However we can reproduce it when we want to register checksum. I am posting whole errors that we see in the client side and server logs in case it might be useful.

a test script:
```
import os, os.path
from irods.session import iRODSSession
env_file = os.getenv('IRODS_ENVIRONMENT_FILE', os.path.expanduser('~/.irods/irods_environment.json'))
with iRODSSession(irods_env_file=env_file) as session:
    pass
obj = session.data_objects.get("/set/home/u0137480/10GB.bin")
print(obj.chksum())
```

client side errors:
```
Traceback (most recent call last):
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/message/__init__.py", line 180, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/connection.py", line 114, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/message/__init__.py", line 270, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/message/__init__.py", line 182, in _recv_message_in_len
    buf = sock.recv(size_left)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u0137480/test/test_41553.py", line 10, in <module>
    print(obj.chksum())
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/data_object.py", line 101, in chksum
    return self.manager.chksum(self.path, **options)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/manager/data_object_manager.py", line 191, in chksum
    response = conn.recv(return_message = msg_retn)
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/connection.py", line 125, in recv
    raise NetworkException("Could not receive server response")
irods.exception.NetworkException: Could not receive server response
Exception ignored in: <function Connection.__del__ at 0x7f695dcb4280>
Traceback (most recent call last):
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/connection.py", line 90, in __del__
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/connection.py", line 303, in disconnect
  File "/home/u0137480/miniconda3/envs/eximious/lib/python3.9/site-packages/irods/connection.py", line 106, in send
irods.exception.NetworkException: Unable to send message
```

logs:
```
[2023-03-14T08:39:26.046Z][icts-p-cloud-rdm-leu-1] irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"Agent process [487674] exited with status [1]","server_host":"set.irods.icts.kuleuven.be","server_pid":110,"server_timestamp":"2023-03-14T08:39:26.045Z","server_type":"agent_factory"}
[2023-03-14T08:39:26.026Z][icts-p-cloud-rdm-leu-1] irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/rodsAgent.cpp:588:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:160:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:850:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]\n\n","request_api_name":"DATA_OBJ_CHKSUM_AN","request_api_number":629,"request_api_version":"d","request_client_user":"u0137480","request_host":"127.0.0.1","request_proxy_user":"u0137480","request_release_version":"rods4.3.0","server_host":"set.irods.icts.kuleuven.be","server_pid":487674,"server_timestamp":"2023-03-14T08:39:26.025Z","server_type":"agent"}
[2023-03-14T08:39:26.026Z][icts-p-cloud-rdm-leu-1] irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/rsApiHandler.cpp:560:int readAndProcClientMsg(rsComm_t *, int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:198:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:528:irods::error ssl_read_msg_header(irods::plugin_context &, void *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]\n\n","request_api_name":"DATA_OBJ_CHKSUM_AN","request_api_number":629,"request_api_version":"d","request_client_user":"u0137480","request_host":"127.0.0.1","request_proxy_user":"u0137480","request_release_version":"rods4.3.0","server_host":"set.irods.icts.kuleuven.be","server_pid":487674,"server_timestamp":"2023-03-14T08:39:26.025Z","server_type":"agent"}
[2023-03-14T08:39:26.026Z][icts-p-cloud-rdm-leu-1] irods stdout | {"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/core/src/rsApiHandler.cpp:357:int sendApiReply(rsComm_t *, int, int, void *, bytesBuf_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:1279:irods::error sendRodsMsg(irods::network_object_ptr, const char *, const bytesBuf_t *, const bytesBuf_t *, const bytesBuf_t *, int, irodsProt_t) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']\n\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:945:irods::error ssl_send_rods_msg(irods::plugin_context &, const char *, const bytesBuf_t *, const bytesBuf_t *, const bytesBuf_t *, int, irodsProt_t) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [Write message header failed.]\n\t\t\t[-]\t/irods_source/lib/core/src/sockComm.cpp:497:irods::error writeMsgHeader(irods::network_object_ptr, const msgHeader_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [Wrote -1 expected 140.]\n\t\t\t\t[-]\t/irods_source/plugins/network/src/ssl.cpp:896:irods::error ssl_write_msg_header(irods::plugin_context &, const bytesBuf_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [Wrote -1 expected 140.]\n\n","request_api_name":"DATA_OBJ_CHKSUM_AN","request_api_number":629,"request_api_version":"d","request_client_user":"u0137480","request_host":"127.0.0.1","request_proxy_user":"u0137480","request_release_version":"rods4.3.0","server_host":"set.irods.icts.kuleuven.be","server_pid":487674,"server_timestamp":"2023-03-14T08:39:26.025Z","server_type":"agent"}
```

Some other inputs:
- we have a simple resource hierarchy and no replication
- simple setup with no consumers
- after a data upload with the same error is completed, we can see the data object in question is in "good" state
- I dont see this error for 1GB

**Comment by mstfdkmn** [comment] 2023-03-14 10:06
One more remark: calculating and registering checksum by `ichksum -Kv` and `msiDataObjChksum` did work without any issue.

**Comment by jpmcfarland** [comment] 2023-03-14 11:13
> 
> Some other inputs:
> 
> * we have a simple resource hierarchy and no replication
> * simple setup with no consumers
> * after a data upload with the same error is completed, we can see the data object in question is in "good" state
> * I dont see this error for 1GB

Hmm, one idea is that this is caused by a network timeout between two machines, the provider and a consumer.  If the issue is replicated with a single provider machine, that narrows down where the issue could be: somewhere between the server and client.  If this is the case, a poor connection on the client's side (WiFi, home ADSL modem, etc.) would play a large role.  Unfortunately, I see this behavior while using a client machine on a wired network logically adjacent to the server network.  That said, it is still time and not file size that dictates when I see the error.  I'll see if I can find a solid time threshold.

**Comment by mstfdkmn** [comment] 2023-03-14 14:25
It might be indeed because of a network timeout. I tried this at the office which I guess there is not a poor connection on the client's side/the same network. 
In order to offer an alternative solution to our users who cannot calculate and register checksum for large files due to this issue, we thought that calling `msiDataObjChksum` as a rule could be an option. But regarding with this I observed some strange results:

- The msi call code snippet below time to time works fine for 10GB file,
- Time to time it results in the same error,
- Even if it results in the same errors, I guess it registers the checksum - but not immediately,
- Increasing the default value for `session.connection_timeout = 300` didnt help
- It always worked for the small-size files.
- Calling this `msiDataObjChksum`  by iCommnds has never failed - `irule -r irods_rule_engine_plugin-irods_rule_language-instance -F checksum.r`
- Calling the second script (calling iCommands by subprocess) below never failed, or generated the same errors

@d-w-moore could you confirm the first script below looks okay to you? Also could you comment what differences there are between calling an iCommand and calling and msi in terms of PRC?

calling msi
```
import os, os.path
import textwrap
from irods.session import iRODSSession
from irods.rule import Rule

env_file = os.getenv('IRODS_ENVIRONMENT_FILE', os.path.expanduser('~/.irods/irods_environment.json'))
with iRODSSession(irods_env_file=env_file) as session:
    pass
rule_body = textwrap.dedent('''\
                                msiSplitPath(*dataObject,*Coll,*File);
                                writeLine("serverLog","Collection is *Coll and file is *File");
                                msiMakeGenQuery("DATA_CHECKSUM","DATA_NAME = '*File' AND COLL_NAME = '*Coll'",*GenQInp);
                                msiExecGenQuery(*GenQInp,*GenQOut);
                                foreach(*GenQOut) {
                                    msiGetValByKey(*GenQOut,"DATA_CHECKSUM",*chkSumS);
                                    msiDataObjChksum(*dataObject,*Flags,*chkSum);
                                    writeLine("serverLog","Saved checksum for file *File is *chkSumS, new checksum is *chkSum");
                                    }
                            ''')


input_params = { "*dataObject": '/set/home/u0137480/10GB.bin1' ,
                 "*Flags": 'forceChksum='
                }

output = 'ruleExecOut'

r = Rule( session, body=rule_body, instance_name = 'irods_rule_engine_plugin-irods_rule_language-instance',
        params=input_params, output='ruleExecOut')
r.execute()
```

calling iCommands
```
import os, os.path
from irods.session import iRODSSession
import subprocess

env_file = os.getenv('IRODS_ENVIRONMENT_FILE', os.path.expanduser('~/.irods/irods_environment_prc.json'))
with iRODSSession(irods_env_file=env_file) as session:
    pass
obj = "/set/home/u0137480/10GB.bin1"
result = subprocess.Popen(f"ichksum -fv {obj}",
                              shell=True,
                              stdout=subprocess.PIPE,
                              universal_newlines=True).communicate()[0]
print(result)
```

**Comment by kript** [comment] 2023-03-14 19:50
Hi folks, when this happened to us using the icommands we found [adjusting the TCP keepalive](https://docs.irods.org/4.2.11/system_overview/troubleshooting/#firewalls-dropping-long-idle-connections-during-parallel-transfer) times helped, no matter the version.

**Comment by d-w-moore** [comment] 2023-03-20 04:20
@kript - I see, makes sense.  That may be a good angle to pursue and a good area to fix, especially with  deadlines coming up for 4.2.12 .  Thanks!

**Comment by jefscheepers** [comment] 2023-03-21 09:01
Hello all, I'm a colleague of @mstfdkmn. 
I just wanted to make a possible link:

Recently, one of our colleagues made an issue for the iRODS Globus Connector: https://github.com/irods/irods_client_globus_connector/issues/55.
The problem was that we got a timeout when Globus was calculating the checksum. 
In this issue, JustinKyleJames mentions the Checksum operation had been updated for 4.3.0.
Is there any way this can be related?


I hope I'm not complicating this issue further, was just curious :)

**Comment by d-w-moore** [comment] 2023-03-21 13:25
@jefscheepers I think it could easily be related, as it is another situation in which an expensive operation grinds away in the server and the client is left waiting.  TCP keepalive packets would then be the only thing keeping the connection active. The Globus issue does give us a couple more  data points in the search for the root of the timeout problem, so thanks for the report! : )

**Comment by d-w-moore** [comment] 2023-03-29 05:54
I believe I've reproduced this, or at least the nearest equivalent on a simple iRODS system.
If PRC is running from  [this development branch](https://github.com/d-w-moore/python-irodsclient/tree/connection_timeout.Main), the  below script should (given typical checksum times I've seen on my system) produce the `NetworkException` due to the iRODS server timing out on the checksumming of a large (4GB) file -
```
#!/usr/bin/env python3
# register_large_file_with_chksum.py
import os
import irods.test.helpers as h
import irods.keywords as kw

logical = s = d = r = None

def create_and_register_file(size = 4*1024**3):
    global d,r,s, logical
    s=h.make_session()
    r = s.resources.create( 'hello', 'unixfilesystem', host='localhost')

    PHYS = '/tmp/thing'
    if os.stat(PHYS).st_size != size:
        print("Creating large file...", end=' ', flush=True)

        rand=os.urandom(1024)
        with open(PHYS,'wb') as f:
            while size > 0:
               i = f.write(rand)
               size -= i
        
        print(".\n")
    else:
        print("Large file of desired size already exists.")

    logical = h.home_collection(s) + '/thing'

    # Operations must respond within 3 seconds.
    s.connection_timeout = 3.0
    s.cleanup()

    s.data_objects.register(PHYS, logical, **{kw.REG_CHKSUM_KW: '', kw.RESC_NAME_KW: r.name})
    d = s.data_objects.get(logical)
    print ('data object = ',d)

try:
    create_and_register_file()

finally:
    # Let further connections have the default timeout.
    s.connection_timeout = None
    s.cleanup()

    try:    d = s.data_objects.get(logical)
    except: pass
    if d:
        d.unregister()
    if r:
        r.remove()
```

Sample session follows.
```
$ python register_large_file_with_chksum.py 
timeout = 120.0
timeout = 120.0
Large file of desired size already exists.
timeout = 3.0
timeout = 120.0
Traceback (most recent call last):
  File "/home/daniel/python-irodsclient/irods/connection.py", line 114, in recv
    msg = iRODSMessage.recv(self.socket)
  File "/home/daniel/python-irodsclient/irods/message/__init__.py", line 273, in recv
    rsp_header_size = _recv_message_in_len(sock, 4)
  File "/home/daniel/python-irodsclient/irods/message/__init__.py", line 183, in _recv_message_in_len
    buf = sock.recv(size_left, socket.MSG_WAITALL)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "register_large_file_with_chksum.py", line 39, in <module>
    create_and_register_file()
  File "register_large_file_with_chksum.py", line 34, in create_and_register_file
    s.data_objects.register(PHYS, logical, **{kw.REG_CHKSUM_KW: '', kw.RESC_NAME_KW: r.name})
  File "/home/daniel/python-irodsclient/irods/manager/data_object_manager.py", line 559, in register
    response = conn.recv()
  File "/home/daniel/python-irodsclient/irods/connection.py", line 125, in recv
    raise NetworkException("Could not receive server response")
irods.exception.NetworkException: Could not receive server response

```

**Comment by d-w-moore** [comment] 2023-03-29 06:13
@jpmcfarland - Note: If in your experiment you not running the latest PRC,  you can probably just cherry-pick the commit that reads **"fix connection timeouts"** to whatever branch / version you are running from, to in your re-attempting the long put( ) operation.

**Comment by jpmcfarland** [comment] 2023-05-10 12:26
Following advice from this thread:

https://groups.google.com/g/irod-chat/c/ywPHhF04GtQ/m/RJya21_VAAAJ

We set the `tcp_keepalive_time` of our ICAT server to match the provider and resource servers `tcp_keepalive_time`: to 120 down from 1800 seconds.  So far, this appears to have done the trick for us.  We are still testing.

**Comment by alanking** [comment] 2023-05-11 13:27
It seems that this may be an ongoing discussion, but a fix has been merged for the next release. @d-w-moore - Please close if complete or advise on next steps.

**Comment by d-w-moore** [comment] 2023-05-11 13:37
Closing for now.  @jpmcfarland , if this interacts in any way negatively with your prescriptions /use-cases (esp. wrt. TCP keepalive and/or network connections in general) please re-open this or log as another issue! Thanks for bringing this particular issue to our attention.

**Closed by d-w-moore** 2023-05-11 13:37 UTC
Labels: bug, consortium-member

**Comment by jpmcfarland** [comment] 2023-05-11 14:59
@d-w-moore It did not, actually, but I will certainly be testing it.  My tests all seemed fine, but it appears another's tests had problems, and without any _significant_ apparent difference to the tests (up to 9GB transfer instead of only 8GB).  We will continue testing with the new settings and the newest commits here and I will open a new issue referencing this one if it becomes necessary.

Thanks for all the help!
