### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by pdonorio** [irods/python-irodsclient#27] opened 2015-11-18 10:30 UTC
This library does not seem to work with Python 3:

``` bash
$ pip3 install --upgrade git+git://github.com/irods/python-irodsclient.git

$ python3

>>> from irods.session import iRODSSession
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/irods/session.py", line 1, in <module>
    from irods.query import Query
  File "/usr/local/lib/python3.4/dist-packages/irods/query.py", line 5, in <module>
    from irods.message import (
  File "/usr/local/lib/python3.4/dist-packages/irods/message/__init__.py", line 7, in <module>
    from irods.message.message import Message
  File "/usr/local/lib/python3.4/dist-packages/irods/message/message.py", line 5, in <module>
    from irods.message.ordered import OrderedProperty, OrderedMetaclass, OrderedClass
  File "/usr/local/lib/python3.4/dist-packages/irods/message/ordered.py", line 23
    key = lambda (name, property): property._creation_counter,
                 ^
SyntaxError: invalid syntax
```

Are there any plan for adding it? I could give a hand if needed.

Thanks,
Paolo

**Comment by adetorcy** [comment] 2015-11-23 17:19
Please have at it. I am not working on Python 3 support at the moment.
Thanks a lot,

A

**Comment by pdonorio** [comment] 2015-11-24 09:43
My colleague tested a raw conversion with 2to3 of the library and it kind of worked.

My idea is to fork, then go with conversion as a base and then write a `_compat.py` file to solve all the problems for compatibility. This could be a good example:
https://github.com/mitsuhiko/jinja2/blob/master/jinja2/_compat.py

The main problem is that i have no knowledge of how the library works, so i may need your help with any strange behavior. How does that sound?

Paolo

**Comment by adetorcy** [comment] 2015-11-24 19:26
What about a single source approach? This project would be a good candidate for it, since for Python 2 we're only supporting 2.7, and for Python 3 I doubt we will need to support anything older than 3.3.

**Comment by pdonorio** [comment] 2015-11-25 10:08
Sorry, i didn't mean to fork and leave it as a separate project.
I would work for compatibility on both python2 and 3 but it would be easier to start from python 3 for me. 
Yes, That support would be 2.7+ and 3.3+.

After all the work i'd go with a pull request to rejoin back.
Only problem i have no idea when to focus on it, probably not before Christmas.

Paolo

**Comment by adetorcy** [comment] 2015-11-25 16:44
No worries. By single source I meant a single codebase that's python 2/3 compatible.

**Comment by colin-nolan** [comment] 2016-08-12 10:35
Is there any update on Python 3 support?

**Comment by pdonorio** [comment] 2016-08-13 08:08
Hello @colin-nolan, 
I had no chances to work this out, so far.

I may have it a try somewhere in October, not sure thought.

**Comment by pdonorio** [comment] 2016-11-30 10:39
I could work on this for my open source project. But since I only use GSI authentication for the moment I have to wait for #56

**Comment by pdonorio** [comment] 2017-01-20 08:10
We may have our take on this from next week, since #57 have been merged.

**Comment by muccix** [comment] 2017-02-17 09:08
I'm looking at modifying the source to make it also python3 compatible.

One approach would be using [modernize](https://github.com/mitsuhiko/python-modernize). This would help a lot but adds a dependency from [six](https://pypi.python.org/pypi/six).

Another approach would be using [_compat](https://github.com/pallets/jinja/blob/master/jinja2/_compat.py), adding the file in the python-irodsclient project.

@adetorcy do you have any preference?

**Comment by adetorcy** [comment] 2017-02-20 14:36
If we have to support python 3 I am definitely in favor of the single code base approach. 
One issue might be how we deal with unicode. With python 2 I went with the ["unicode sandwich"](nedbatchelder.com/text/unipain/unipain.html) approach (bytes on the outside, unicode on the inside), but you won't do that in python 3.
There are some good pointers [here](https://docs.python.org/3/howto/pyporting.html), which you have probably seen already.
A dependency on six would not be a big deal if necessary, although I would first try with the `--no-six` option. For python 2 we only have to support 2.7. For python 3 I am not sure but I would say 3.4. Sounds reasonable?

**Comment by muccix** [comment] 2017-02-21 08:20
Ok, I'm going to try with the option --no-six at first.
Python 2.7 and 3.4 sounds reasonable.

**Comment by muccix** [comment] 2017-02-28 10:09
I have some problem with this [line](https://github.com/irods/python-irodsclient/blob/master/irods/message/__init__.py#L81) which, as far as I understand, mixes bytes ('\x00\x00\x00\x9c') and strings.

I think  the problem is that 
`msg_header_length = struct.pack(">i", len(msg_header))`
returns a string in py2 and a byte in py3.

Any suggestions?

**Comment by muccix** [comment] 2017-03-01 09:24
I'm getting the following error:

```bash
Traceback (most recent call last):
  File "/code/prc3/irods/test/access_test.py", line 20, in setUp
    self.coll = helpers.make_collection(self.sess, self.coll_path)
  File "/code/prc3/irods/test/helpers.py", line 42, in make_collection
    coll = session.collections.create(path)
  File "/code/prc3/irods/manager/collection_manager.py", line 31, in create
    return self.get(path)
  File "/code/prc3/irods/manager/collection_manager.py", line 14, in get
    query = self.sess.query(Collection).filter(Collection.name == path)
  File "/code/prc3/irods/session.py", line 53, in query
    return Query(self, *args)
  File "/code/prc3/irods/query.py", line 49, in __init__
    self.columns[col] = 1
TypeError: unhashable type: 'Column'

```
Probably py2 in more relaxed in having a unhashable type as key of a dict.

Any idea?

**Comment by muccix** [comment] 2017-03-01 10:05
I should have solved adding __hash__ function to class Column(QueryKey):

**Comment by muccix** [comment] 2017-03-02 10:12
I have another issue with the unicode_test: in Py3 I have to convert the message to a byte, but this is what I get with non standard directory name:

```bash
b'\x00\x00\x00\x9e<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>320</msgLen>            <errorLen>0</errorLen><bsLen>0</bsLen><intInfo>601</intInfo>            </MsgHeader_PI><DataObjInp_PI><objPath>/tempZone/home/rods/test_dir/\xc3\x89ire</objPath><createMode>420</createMode><openFlags>0</openFlags><offset>0</offset><dataSize>-1</dataSize><numThreads>0</numThreads><oprType>0</oprType><KeyValPair_PI><ssLen>1</ssLen><keyWord>dataType</keyWord><svalue>generic</svalue></KeyValPair_PI></DataObjInp_PI>'
```

Where the folder name is replaced by "/\xc3\x89ire". 
Any idea on how this could be solved?

**Comment by muccix** [comment] 2017-03-13 10:46
A new version working with both py2 and py3 is ready (see https://github.com/irods/python-irodsclient/pull/61)!
All tests are ok.
Please let me know if there is something you would like me to change.

**Comment by adetorcy** [comment] 2017-03-13 15:38
Thank you very much for your contribution.
Is anyone following your python3 branch? If not I would suggest resetting it to your last working commit and rebasing it onto master (instead of merging, to keep the history linear as much as possible).

**Comment by muccix** [comment] 2017-03-13 16:12
Submitted a new pull request with squashed commits

**Comment by muccix** [comment] 2017-03-14 08:13
Great to see you have merged the pull request! It could be a good idea to update the README page with the support to python3 (and GSI too).

**Comment by alexlemann** [comment] 2017-05-31 15:59
I have been using `python-irodsclient` in Python 3.6. Are there any issues that I look out for, or can this issue be closed?

**Comment by adetorcy** [comment] 2017-05-31 18:29
There is no outstanding issue that I know of at this point, but I still need to add a Python 3 test suite in our CI testing environment before closing this.

**Closed** 2017-08-09 18:55 UTC
Labels: enhancement
