### ISSUE TITLE
'pass' statement together with 'with' not closing session

### ISSUE THREAD

**Issue by mstfdkmn** [irods/python-irodsclient#316] opened 2021-11-22 13:14 UTC
Hello,
It seems that it is not closing the session once the 'pass' statement is used inside the with. Is this normal or related to any issue known (#315)?
Thanks.

You can use the session like open.
```
>>> import os
>>> import ssl
>>> from irods.session import iRODSSession
>>> try:
...     env_file = os.environ['IRODS_ENVIRONMENT_FILE']
... except KeyError:
...     env_file = os.path.expanduser('~/.irods/irods_environment.json')
...
>>> ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
>>> ssl_settings = {'ssl_context': ssl_context}
>>> with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
...     pass
...
>>> collection = session.collections.get("/myZone/home/myHome")
>>> print(collection.path)
/myZone/home/myHome
```

Logs:

```
Nov 22 14:00:56 pid:42715 remote addresses: XXX.X.X.X, 2a02:2c40:0:21::3306:28 ERROR: [-]       /work/server/core/src/rsApiHandler.cpp:541:int readAndProcClientMsg(rsComm_t *, int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
        [-]     /work/lib/core/src/sockComm.cpp:197:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     /work/plugins/network/ssl/libssl.cpp:571:irods::error ssl_read_msg_header(irods::plugin_context &, void *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Nov 22 14:00:56 pid:42715 remote addresses: 2a02:2c40:0:21::3306:28 ERROR: [-]  /work/server/core/src/rodsAgent.cpp:556:int runIrodsAgentFactory(sockaddr_un) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
        [-]     /work/lib/core/src/sockComm.cpp:159:irods::error sockAgentStop(irods::network_object_ptr) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
                [-]     /work/plugins/network/ssl/libssl.cpp:951:irods::error ssl_agent_stop(irods::plugin_context &) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]

Nov 22 14:00:56 pid:108  ERROR: Agent process [42715] exited with status [64]
```

**Comment by d-w-moore** [comment] 2021-11-22 15:30
@mstfdkmn This is actually expected behavior. 
The purpose of `cleanup` is to destroy all connection objects in the idle and active connection pools held by the session, ie. return the session object to the state it was in before the first connection to the server was made.
If you run your script with the following line immediately before and after the collection open( ) statement, just so:
```
 print('BEFORE: active',session.pool.active,' ; idle',session.pool.idle)
 collection = session.collections.get("/myZone/home/myHome")
 print(collection.path)
 print('AFTER: active',session.pool.active,' ; idle',session.pool.idle)
```
You should see the following:
```
BEFORE: active set()  ; idle set()
/myZone/home/myHome
AFTER:  active set()  ; idle {<irods.connection.Connection object at 0x7fb4fd6350b8>}
```
In this way,  applications can use cleanup ( ) to - in effect - inform the server it should not expect further operations for a while.

If what's needed is a close() method and closed attribute similar (to file objects in Python), to guard against further use of the session, this could be a separate feature request !

**Comment by mstfdkmn** [comment] 2021-11-23 12:23
Thanks for explanation.

In our current use case we don't see any need to a 'close' type method/attribute for the moment as long as this is good for you/all.

However the following is for your information. I see even if I use the cleanup() method after the last script wait for a while, it seems I can still use the session. (Btw, I dont see anymore any errors on logs if I use only the cleanup, not waiting-sleep). What does in this sense the '... should not expect further operations **for a while**' mean? 

```
import os
import ssl
from irods.session import iRODSSession
try:
    env_file = os.environ['IRODS_ENVIRONMENT_FILE']
except KeyError:
    env_file = os.path.expanduser('~/.irods/irods_environment.json')

ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile=None, capath=None, cadata=None)
ssl_settings = {'ssl_context': ssl_context}

with iRODSSession(irods_env_file=env_file, **ssl_settings) as session:
    pass

print('BEFORE: active',session.pool.active,' ; idle',session.pool.idle)
collection = session.collections.get("/myZone/home/myHome")
print(collection.path)
print('AFTER: active',session.pool.active,' ; idle',session.pool.idle)
session.cleanup()
import time
time.sleep(20)
data_obj = session.data_objects.get("/myZone/home/myHome/test.txt")
print(data_obj.path)
```

```
BEFORE: active set()  ; idle set()
/myZone/home/myHome
AFTER: active set()  ; idle {<irods.connection.Connection object at 0x7f6ff7e85fa0>}
/myZone/home/myHome/test.txt
```

**Comment by d-w-moore** [comment] 2021-11-23 15:03
@mstfdkmn From a practical standpoint, a client should shut down a connection   if it does not expect to use that connection within the server's  [timeout ](https://github.com/irods/python-irodsclient#maintaining-a-connection) interval.  (If a connection object in the pool were held open longer than that interval, and then used, an error would result because the server would have dropped the connection.  This is the reasoning behind cleanup( ): the client's session object can be used again after an arbitrary or indeterminate amount of time, or never again (to include the case of a client program exiting), and the server is fine with that.

**Comment by mstfdkmn** [comment] 2021-11-23 17:09
Thanks again for clarifying. Also, I should have looked at README for the default timeout.

**Comment by d-w-moore** [comment] 2021-11-23 18:05
@mstfdkmn No problem! : ) Should we close this issue ?

**Comment by mstfdkmn** [comment] 2021-11-23 18:24
Please!

**Closed** 2021-11-23 19:37 UTC
Labels: question
