### ISSUE TITLE
Tag 1.1.9 - `Quota` feature is expected and described in docs but is absent

### ISSUE THREAD

**Issue by IanVermes** [irods/python-irodsclient#509] opened 2024-02-05 01:25 UTC
I'm trying to use the new `Quota` [#479] feature documented in the [README.md#quotas-v119](https://github.com/irods/python-irodsclient/blob/main/README.md#quotas-v119) to be able measure quota usage.

The README records it as available in 1.1.9. But unfortunately the documentation does not match the expectation -- I get ImportErrors.

**Installation**
```bash
$ poetry show python-irodsclient
 name         : python-irodsclient     
 version      : 1.1.9                  
 description  : A python API for iRODS 

dependencies
 - defusedxml *
 - PrettyTable >=0.7.2
 - six >=1.10.0
 ```
 
 And then when importing:
 ```python
 from irods.models import Quota

ImportError: cannot import name 'Quota' from 'irods.models' (/path/to/my/pacakge/.venv/lib/python3.11/site-packages/irods/models.py)
```

The expected `Quota` class definition is not in tag 1.1.9, but is on your main branch.

**Comment by trel** [comment] 2024-02-05 01:47
Ah, I see the misunderstanding.  That header is saying that it has been added 'since' 1.1.9... which is... not clear.

We will change that to read 2.0.0 which will be out within a week or so.  Apologies.

We will close this issue once we update the documentation to match the release.

**Comment by trel** [comment] 2024-02-05 01:49
Also, can be considered a duplicate of https://github.com/irods/python-irodsclient/issues/484

**Closed** 2024-02-05 17:38 UTC
Labels: duplicate, documentation

**Comment by IanVermes** [comment] 2024-02-05 18:59
Thank you!
